name: Deploy to Private Repository

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Create key.js with environment secrets
      - name: Create key.js with secrets
        run: |
          echo "const ENV = { ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}', RPC_NODE_KEY: '${{ secrets.RPC_NODE_KEY }}' };" > key.js

      # Debug: List files before deployment
      - name: Debug: List repository files
        run: ls -la

      # Step 3.5: Debug private repository access
      - name: Test private repository access
        run: |
          echo "Testing private repository access..."
          git ls-remote https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jalvarez212/ethnotary_prod.git


      # Step 3: Deploy to the private repository
      - name: Deploy to Private Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: jalvarez212/ethnotary_prod # Private repository name
          publish_branch: main # Branch to push to in the private repository
          publish_dir: . # Push everything in the current directory
