name: Deploy and Generate key.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate key.js file
      run: |
        mkdir -p public
        echo "export const secrets = {" > public/key.js
        echo "  ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}'," >> public/key.js
        echo "  RPC_NODE_KEY: '${{ secrets.RPC_NODE_KEY }}'" >> public/key.js
        echo "};" >> public/key.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
