name: Deploy to Private Repository

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "This workflow is triggered!"

      # Step 2: Create key.js with environment secrets
      - name: Create key.js with secrets
        run: |
          echo "const ENV = { ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}', RPC_NODE_KEY: '${{ secrets.RPC_NODE_KEY }}' };" > key.js

      # Debug: List files in the workspace
      - name: Debug: List workspace files
        run: ls -la

      # Step 3: Deploy using peaceiris/actions-gh-pages
      - name: Deploy to Private Repository (via peaceiris)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: jalvarez212/ethnotary_prod
          publish_branch: main
          publish_dir: . # Push everything in the current directory

      # Step 4: Fallback: Deploy using manual git commands
      - name: Deploy to Private Repository (manual fallback)
        if: failure() # Run only if Step 3 fails
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git init
          git add .
          git commit -m "Fallback Deploy to private repository"
          git branch -M main
          git remote add origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jalvarez212/ethnotary_prod.git
          git push -f origin main
