name: Deploy to Private Repository

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Create key.js with environment secrets
      - name: Create key.js with secrets
        run: |
          echo "const ENV = { ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}', RPC_NODE_KEY: '${{ secrets.RPC_NODE_KEY }}' };" > key.js

      # Debug: List files before deployment
      - name: Debug: List repository files
        run: ls -la

      # Step 3: Push the repository to the private repository
      - name: Push to Private Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git init
          git add .
          git commit -m "Deploy to private repository"
          git branch -M main
          git remote add origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jalvarez212/ethnotary_prod.git
          git push -f origin main
