name: Deploy to Private Repository

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Create key.js with environment secrets
      - name: Create key.js with secrets
        run: |
          echo "const ENV = { ETHERSCAN_API_KEY: '${{ secrets.ETHERSCAN_API_KEY }}', RPC_NODE_KEY: '${{ secrets.RPC_NODE_KEY }}' };" > key.js

      # Debug: List files in the workspace
      - name: Debug: List workspace files
        run: ls -la

      # Step 3: Deploy to private repository
      - name: Deploy to Private Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: jalvarez212/ethnotary_prod # Replace with your private repository name
          publish_branch: main # Target branch in private repository
          publish_dir: . # Push everything in the current directory
          force_orphan: true # Force an orphan commit (overwrite everything)
